#!/usr/bin/env python3
"""Regenerate tests/musicxml_archive_fixtures.inc.

Three .mxl archives holding one identical two-note MusicXML member, so a
deflate path and a stored path can be compared against the same parse. The
archive bytes are embedded verbatim by the test; nothing is compressed or
packed at test time, which would hide a format mistake inside a format
mistake. Python's zipfile is the independent writer: the reader under test
shares no code with it.

Usage:
  python3 scripts/make_musicxml_archive_fixture.py [OUTPUT.inc]
"""
import io
import struct
import sys
import zipfile
import zlib

XML = (
    "<score-partwise><part-list><score-part id='P1'><part-name>Piano</part-name></score-part>"
    "</part-list><part id='P1'><measure number='1'>"
    "<note><pitch><step>C</step><octave>4</octave></pitch><duration>480</duration></note>"
    "<note><pitch><step>E</step><octave>4</octave></pitch><duration>480</duration></note>"
    "</measure></part></score-partwise>"
)
CONTAINER = (
    "<?xml version='1.0' encoding='UTF-8'?>"
    "<container version='1.0' xmlns='http://www.idpf.org/2011/opf/'>"
    "<rootfiles><rootfile full-path='score.musicxml' "
    "media-type='application/vnd.recordare.musicxml'/></rootfiles></container>"
)


def build(entries, method):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", method) as archive:
        for name, payload in entries:
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = method
            archive.writestr(info, payload)
    return buf.getvalue()


def raw_deflate(payload, level):
    """A raw deflate member body, independent of zipfile's own framing."""
    compressor = zlib.compressobj(level, zlib.DEFLATED, -15)
    return compressor.compress(payload) + compressor.flush()


def build_raw(entries):
    """Archive from precompressed members: (name, payload, compressed bytes)."""
    body = bytearray()
    directory = bytearray()
    for name, payload, compressed in entries:
        offset = len(body)
        crc = zlib.crc32(payload) & 0xFFFFFFFF
        body += struct.pack("<IHHHHHIIIHH", 0x04034b50, 20, 0, 8, 0, 0, crc,
                            len(compressed), len(payload), len(name), 0)
        body += name.encode() + compressed
        directory += struct.pack("<IHHHHHHIIIHHHHHII", 0x02014b50, 20, 20, 0, 8, 0, 0, crc,
                                 len(compressed), len(payload), len(name), 0, 0, 0, 0, 0,
                                 offset)
        directory += name.encode()
    out = bytearray(body + directory)
    out += struct.pack("<IHHHHIIH", 0x06054b50, 0, 0, len(entries), len(entries),
                       len(directory), len(body), 0)
    return bytes(out)


def big_payload():
    head = XML[: XML.index("<measure")]
    tail = "</part></score-partwise>"
    first = ("<measure number='1'><note><pitch><step>C</step><octave>4</octave></pitch>"
             "<duration>480</duration></note><note><pitch><step>E</step><octave>4</octave></pitch>"
             "<duration>480</duration></note></measure>")
    measures = "".join(
        f"<measure number='{i}'><note><pitch><step>D</step><octave>4</octave></pitch>"
        f"<duration>480</duration></note></measure>" for i in range(2, 901))
    return (head + first + measures + tail).encode()


def main():
    output = sys.argv[1] if len(sys.argv) > 1 else "tests/musicxml_archive_fixtures.inc"
    cases = [
        ("kMxlDeflate", build([("META-INF/container.xml", CONTAINER), ("score.musicxml", XML)],
                              zipfile.ZIP_DEFLATED)),
        ("kMxlDeflateNoContainer", build([("score.musicxml", XML)], zipfile.ZIP_DEFLATED)),
        ("kMxlStored", build([("META-INF/container.xml", CONTAINER), ("score.musicxml", XML)],
                             zipfile.ZIP_STORED)),
        # A member whose deflate stream uses only stored blocks: after a
        # Huffman block header the bit reader must hand the stored block its
        # bytes at the right bit boundary.
        ("kMxlStoredBlocks", build_raw([
            ("META-INF/container.xml", CONTAINER.encode(), raw_deflate(CONTAINER.encode(), 9)),
            ("score.musicxml", (XML + "<!-- " + "x" * 600 + " -->").encode(),
             raw_deflate((XML + "<!-- " + "x" * 600 + " -->").encode(), 0)),
        ])),
        # A member big enough to split across dynamic blocks, so distances
        # grow past the first screenful of output.
        ("kMxlMultiBlock", build_raw([
            ("META-INF/container.xml", CONTAINER.encode(), raw_deflate(CONTAINER.encode(), 9)),
            ("score.musicxml", big_payload(), raw_deflate(big_payload(), 9)),
        ])),
    ]
    lines = [
        "// Generated by scripts/make_musicxml_archive_fixture.py; regenerate, do not hand-edit.",
        "// Five archives: deflate with META-INF/container.xml, deflate without it,",
        "// stored with it, a stored-blocks member, and a multi-block dynamic",
        "// member (900 measures) that exercises long-distance copies.",
        "",
    ]
    for name, data in cases:
        body = ",".join(str(byte) for byte in data)
        lines.append(f"static const unsigned char {name}[] = {{\n{body}\n}};\n")
    with open(output, "w") as handle:
        handle.write("\n".join(lines))
    print("wrote " + output + ": " + ", ".join(f"{name}={len(data)} bytes" for name, data in cases))


if __name__ == "__main__":
    main()
