name: build

on:
  push:
  pull_request:

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --parallel 2
      - name: Test
        run: ctest --test-dir build --output-on-failure
